name: ms-graph-api-CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

defaults: { run: { shell: bash } }

on: [push]

jobs:
  build:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc-version: ['9.6', '9.4', '9.2', '9.0', '8.10']
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Setup Haskell tools
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc-version }}
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - name: Stack build and test
        run: |
          stack build
          stack test

  # ci:
  #   name: CI
  #   runs-on: ubuntu-latest # or macOS-latest, or windows-latest
  #   steps:
  #     - name: git checkout
  #       uses: actions/checkout@v3
  #     - name: Setup tools
  #       uses: haskell/actions/setup@v2
  #       with:
  #         ghc-version: '8.8.4' # Exact version of ghc to use
  #         # cabal-version: 'latest'. Omitted, but defaults to 'latest'
  #         enable-stack: true
  #         stack-version: 'latest'
  #     - name: stack build and test
  #       run: |
  #         stack build
  #         stack test
