name: ms-graph-api-CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

defaults: { run: { shell: bash } }

jobs:
  build:
    name: stackage ${{ matrix.stack-resolver }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        stack-resolver: ['lts-20.24']
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: ms-graph-api : Setup compiler, build and test
        working-directory: ./ms-graph-api
        run: |
          stack build --resolver ${{ matrix.stack-resolver }}
          stack test
      - name: ms-azure-api : Setup compiler, build and test
        working-directory: ./ms-azure-api
        run: |
          stack build --resolver ${{ matrix.stack-resolver }}
          stack test
      - name: ms-auth : Setup compiler, build and test
        working-directory: ./ms-auth
        run: |
          stack build --resolver ${{ matrix.stack-resolver }}
          stack test
